French translate
Vectorial1024/Desynchronized pull request #17
Opened 2019-05-16 21:18 UTC by Mihokyo

Hey, i 've do the french translate 

But i got actualy a problem for the gender for the kidnapped people

An exemple for "my cousin":

In french we say
For a girl : "Ma cousine"
For a man : "Mon cousin"

If i got a way to know the {0} gender it would be nice. Or use something like {PAWN_gender ? man : girl}

2019-05-17 09:56 UTC, Vectorial1024 commented
First of all, many thanks for the French translation! You will be credited in the mod's description/info pages/places.

Second, about the translation problem. I understand you have different genders for words in French. RimWorld actually allows us to use some symbols to help with such translation. See link: https://ludeon.com/forums/index.php?topic=43979.0

Here's some French translation data from the game as an example:
```
<!-- EN: my cousin {0} died -->
<MyCousinDied.stages.my_cousin_died.label>{0_gender ? mon : ma : mon/ma} cousi{0_gender ? n : ne : n(e)} {0} est mor{0_gender ? t : te : t(e)}</MyCousinDied.stages.my_cousin_died.label>
<!-- EN: My cousin died. My own flesh and blood... -->
<MyCousinDied.stages.my_cousin_died.description>Mon/ma cousin(e) est mort(e). Ma famille vacille…</MyCousinDied.stages.my_cousin_died.description>
```

Please update the translations (if needed) using the above method. (I am not sure whether you need to open another pull request afterwards.)

Again, many thanks for the translation!

2019-05-17 10:01 UTC, Vectorial1024 requested changes
First of all, many thanks for the French translation! You will be credited in the mod's description/info pages/places.

Second, about the translation problem. I understand you have different genders for words in French. RimWorld actually allows us to use some symbols to help with such translation. See link: https://ludeon.com/forums/index.php?topic=43979.0

Here's some French translation data from the game as an example:
```
<!-- EN: my cousin {0} died -->
<MyCousinDied.stages.my_cousin_died.label>{0_gender ? mon : ma : mon/ma} cousi{0_gender ? n : ne : n(e)} {0} est mor{0_gender ? t : te : t(e)}</MyCousinDied.stages.my_cousin_died.label>
<!-- EN: My cousin died. My own flesh and blood... -->
<MyCousinDied.stages.my_cousin_died.description>Mon/ma cousin(e) est mort(e). Ma famille vacille…</MyCousinDied.stages.my_cousin_died.description>
```
Please update the translations (if needed) using the above method. (I am not sure whether you need to open another pull request afterwards.)

Again, many thanks for the translation!

2019-05-17 11:10 UTC, Mihokyo commented
Nice i'm doing it now ! I wasn't sure about this, replace PAWN by 0 would work

2019-05-17 11:13 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <PawnWithGoodOpinionWasKidnapped.stages.my_friend_was_kidnapped.label>Mon ami(e) {0} a été kidnappé(e).</PawnWithGoodOpinionWasKidnapped.stages.my_friend_was_kidnapped.label>
```suggestion
  <PawnWithGoodOpinionWasKidnapped.stages.my_friend_was_kidnapped.label>Mon {0_gender ? ami : amie} {0} a été kidnapp{0_gender ? é : ée }.</PawnWithGoodOpinionWasKidnapped.stages.my_friend_was_kidnapped.label>
```

2019-05-17 11:14 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <PawnWithBadOpinionWasKidnapped.stages.my_rival_was_kidnapped.label>Mon rival {0} a été kidnappé(e).</PawnWithBadOpinionWasKidnapped.stages.my_rival_was_kidnapped.label>
```suggestion
  <PawnWithBadOpinionWasKidnapped.stages.my_rival_was_kidnapped.label>Mon rival {0} a été kidnapp{0_gender ? é : ée }.</PawnWithBadOpinionWasKidnapped.stages.my_rival_was_kidnapped.label>
```

2019-05-17 11:15 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyLoverWasKidnapped.stages.my_lover_was_kidnapped.description>Mon amour a été kidnappé(e). Je suis tellement seul(e).</MyLoverWasKidnapped.stages.my_lover_was_kidnapped.description>
```suggestion
  <MyLoverWasKidnapped.stages.my_lover_was_kidnapped.description>Mon amour a été kidnapp{0_gender ? é : ée }. Je suis tellement seu{0_gender ? l : le }.</MyLoverWasKidnapped.stages.my_lover_was_kidnapped.description>
```

2019-05-17 11:16 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyHalfSiblingWasKidnapped.stages.my_halfsibling_was_kidnapped.label>Mon/Ma demi-frère/soeur {0} a été kidnappé(e).</MyHalfSiblingWasKidnapped.stages.my_halfsibling_was_kidnapped.label>
```suggestion
  <MyHalfSiblingWasKidnapped.stages.my_halfsibling_was_kidnapped.label>M{0_gender ? on : a } demi-{0_gender ? frère : soeur } {0} a été kidnapp{0_gender ? é : ée }.</MyHalfSiblingWasKidnapped.stages.my_halfsibling_was_kidnapped.label>
```

2019-05-17 11:17 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyHalfSiblingWasKidnapped.stages.my_halfsibling_was_kidnapped.description>Mon/Ma demi-frère/soeur a été kidnappé(e). Ma propre chair.. sang...</MyHalfSiblingWasKidnapped.stages.my_halfsibling_was_
```suggestion
  <MyHalfSiblingWasKidnapped.stages.my_halfsibling_was_kidnapped.description>M{0_gender ? on : a } demi-{0_gender ? frère : soeur } a été kidnapp{0_gender ? é : ée }. Ma propre chair.. sang...</MyHalfSiblingWasKidnapped.stages.my_halfsibling_was_kidnapped.description>
```

2019-05-17 11:18 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyGrandparentWasKidnapped.stages.my_grandparent_was_kidnapped.label>Mon grand-parent {0} a été kidnappé.</MyGrandparentWasKidnapped.stages.my_grandparent_was_kidnapped.label>
```suggestion
  <MyGrandparentWasKidnapped.stages.my_grandparent_was_kidnapped.label>M{0_gender ? on : a } grand-{0_gender ? père : mère } {0} a été kidnapp{0_gender ? é : ée }.</MyGrandparentWasKidnapped.stages.my_grandparent_was_kidnapped.label>
```

2019-05-17 11:19 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyGrandparentWasKidnapped.stages.my_grandparent_was_kidnapped.description>Mon grand-parent a été kidnappé.</MyGrandparentWasKidnapped.stages.my_grandparent_was_kidnapped.description>
```suggestion
  <MyGrandparentWasKidnapped.stages.my_grandparent_was_kidnapped.description>M{0_gender ? on : a } grand-{0_gender ? père : mère } {0} a été kidnapp{0_gender ? é : ée }.</MyGrandparentWasKidnapped.stages.my_grandparent_was_kidnapped.description>
```

2019-05-17 11:20 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyCousinWasKidnapped.stages.my_cousin_was_kidnapped.label>Mon/Ma cousin/e {0} a été kidnappé(e).</MyCousinWasKidnapped.stages.my_cousin_was_kidnapped.label>
```suggestion
  <MyCousinWasKidnapped.stages.my_cousin_was_kidnapped.label>M{0_gender ? on : a } cousi{0_gender ? n : ne } {0} a été kidnapp{0_gender ? é : ée }.</MyCousinWasKidnapped.stages.my_cousin_was_kidnapped.label>
```

2019-05-17 11:21 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyCousinWasKidnapped.stages.my_cousin_was_kidnapped.description>Mon/Ma cousin/e a été kidnappé. Ma propre chair.. sang...</MyCousinWasKidnapped.stages.my_cousin_was_kidnapped.description>
```suggestion
  <MyCousinWasKidnapped.stages.my_cousin_was_kidnapped.description>M{0_gender ? on : a } cousi{0_gender ? n : ne } {0} a été kidnapp{0_gender ? é : ée }. Ma propre chair.. sang...</MyCousinWasKidnapped.stages.my_cousin_was_kidnapped.description>
```

2019-05-17 11:22 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyKinWasKidnapped.stages.my_kin_was_kidnapped.label>De ma famille, {0} a été kidnappé.</MyKinWasKidnapped.stages.my_kin_was_kidnapped.label>
```suggestion
  <MyKinWasKidnapped.stages.my_kin_was_kidnapped.label>{0} de ma famille a été kidnapp{0_gender ? é : ée }.</MyKinWasKidnapped.stages.my_kin_was_kidnapped.label>
```

2019-05-17 11:27 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyAuntWasKidnapped.stages.my_aunt_was_kidnapped.description>Ma tante a été kidnappé.</MyAuntWasKidnapped.stages.my_aunt_was_kidnapped.description>
```suggestion
  <MyAuntWasKidnapped.stages.my_aunt_was_kidnapped.description>Ma tante a été kidnappée.</MyAuntWasKidnapped.stages.my_aunt_was_kidnapped.description>
```

2019-05-17 11:27 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyAuntWasKidnapped.stages.my_aunt_was_kidnapped.label>Ma tante {0} a été kidnappé.</MyAuntWasKidnapped.stages.my_aunt_was_kidnapped.label>
```suggestion
  <MyAuntWasKidnapped.stages.my_aunt_was_kidnapped.label>Ma tante {0} a été kidnappée.</MyAuntWasKidnapped.stages.my_aunt_was_kidnapped.label>
```

2019-05-17 11:29 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyLoverWasKidnapped.stages.my_lover_was_kidnapped.label>Mon amour {0} a été kidnappé.</MyLoverWasKidnapped.stages.my_lover_was_kidnapped.label>
```suggestion
  <MyLoverWasKidnapped.stages.my_lover_was_kidnapped.label>Mon amour {0} a été kidnapp{0_gender ? é : ée }.</MyLoverWasKidnapped.stages.my_lover_was_kidnapped.label>
```

2019-05-17 11:29 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MySisterWasKidnapped.stages.my_sister_was_kidnapped.label>Ma soeur {0} a été kidnappé.</MySisterWasKidnapped.stages.my_sister_was_kidnapped.label>
```suggestion
  <MySisterWasKidnapped.stages.my_sister_was_kidnapped.label>Ma soeur {0} a été kidnapp{0_gender ? é : ée }.</MySisterWasKidnapped.stages.my_sister_was_kidnapped.label>
```

2019-05-17 11:30 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MySisterWasKidnapped.stages.my_sister_was_kidnapped.description>Ma soeur a été kidnappé. Ma propre chair.. sang...</MySisterWasKidnapped.stages.my_sister_was_kidnapped.description>
```suggestion
  <MySisterWasKidnapped.stages.my_sister_was_kidnapped.description>Ma soeur a été kidnapp{0_gender ? é : ée }. Ma propre chair.. sang...</MySisterWasKidnapped.stages.my_sister_was_kidnapped.description>
```

2019-05-17 11:31 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyGrandchildWasKidnapped.stages.my_grandchild_was_kidnapped.label>Mon petit-enfant {0} a été kidnappé.</MyGrandchildWasKidnapped.stages.my_grandchild_was_kidnapped.label>
```suggestion
  <MyGrandchildWasKidnapped.stages.my_grandchild_was_kidnapped.label>M{0_gender ? on : a } peti{0_gender ? t : te }-{0_gender ? fils : fille } {0} a été kidnapp{0_gender ? é : ée }.</MyGrandchildWasKidnapped.stages.my_grandchild_was_kidnapped.label>
```

2019-05-17 11:32 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyGrandchildWasKidnapped.stages.my_grandchild_was_kidnapped.description>Mon petit-enfant a été kidnappé Ma propre chair.. sang...</MyGrandchildWasKidnapped.stages.my_grandchild_was_kidnapped.descr
```suggestion
  <MyGrandchildWasKidnapped.stages.my_grandchild_was_kidnapped.description>M{0_gender ? on : a } peti{0_gender ? t : te }-{0_gender ? fils : fille } {0} a été kidnapp{0_gender ? é : ée }. Ma propre chair.. sang...</MyGrandchildWasKidnapped.stages.my_grandchild_was_kidnapped.description>
```

2019-05-17 13:00 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyGrandparentWasKidnapped.stages.my_grandparent_was_kidnapped.description>M{0_gender ? on : a } grand-{0_gender ? père : mère } {0} a été kidnapp{0_gender ? é : ée }.</MyGrandparentWasKidnapped.st
```
Exception in DrawThoughtGroup for MyGrandparentWasKidnapped on M-Vert: System.FormatException: Input string was not in a correct format.
  at System.String.ParseFormatSpecifier (System.String str, System.Int32& ptr, System.Int32& n, System.Int32& width, System.Boolean& left_align, System.String& format) [0x00000] in <filename unknown>:0 
  at System.String.FormatHelper (System.Text.StringBuilder result, IFormatProvider provider, System.String format, System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.String.Format (IFormatProvider provider, System.String format, System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.String.Format (System.String format, System.Object arg0) [0x00000] in <filename unknown>:0 
  at RimWorld.Thought_Memory.get_LabelCap () [0x00000] in <filename unknown>:0 
  at RimWorld.NeedsCardUtility.DrawThoughtGroup (Rect rect, RimWorld.Thought group, Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
RimWorld.NeedsCardUtility:DrawThoughtGroup(Rect, Thought, Pawn)
RimWorld.NeedsCardUtility:DrawThoughtListing(Rect, Pawn, Vector2&)
RimWorld.NeedsCardUtility:DoMoodAndThoughts(Rect, Pawn, Vector2&)
RimWorld.NeedsCardUtility:DoNeedsMoodAndThoughts(Rect, Pawn, Vector2&)
RimWorld.ITab_Pawn_Needs:FillTab_Patch2(Object)
Verse.<DoTabGUI>c__AnonStorey0:<>m__0()
Verse.ImmediateWindow:DoWindowContents(Rect)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
```


I don't know what does it means

2019-05-17 13:02 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <PawnWithGoodOpinionWasKidnapped.stages.my_friend_was_kidnapped.description>Une personne si merveilleuse, tombant entre les mains de l'ennemi. Le/La reverrai-je un jour ?</PawnWithGoodOpinionWasKid
```suggestion
  <PawnWithGoodOpinionWasKidnapped.stages.my_friend_was_kidnapped.description>Une personne si merveilleuse, tombant entre les mains de l'ennemi. {0_gender ? Le : La } reverrai-je un jour ?</PawnWithGoodOpinionWasKidnapped.stages.my_friend_was_kidnapped.description>
```

2019-05-17 13:03 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <PawnWithBadOpinionWasKidnapped.stages.my_rival_was_kidnapped.description>Bien fait. Au moins je ne suis pas prêt de le/la revoir pendant un moment.</PawnWithBadOpinionWasKidnapped.stages.my_rival_
```suggestion
  <PawnWithBadOpinionWasKidnapped.stages.my_rival_was_kidnapped.description>Bien fait. Au moins je ne suis pas prê{PAWN_gender ? t : te } de {0_gender ? le : la } revoir pendant un moment.</PawnWithBadOpinionWasKidnapped.stages.my_rival_was_kidnapped.description>
```

2019-05-17 19:08 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <KnowColonistKidnapped.stages.colonist_kidnapped.description>Un des notres a été kidnappé Je ne trouve pas sûr de rester dans les environs.</KnowColonistKidnapped.stages.colonist_kidnapped.descript
```suggestion
  <KnowColonistKidnapped.stages.colonist_kidnapped.description>Un des nôtres a été kidnappé. Je ne trouve pas sûr de rester dans les environs.</KnowColonistKidnapped.stages.colonist_kidnapped.description>
```

2019-05-17 19:09 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MySonWasKidnapped.stages.my_son_was_kidnapped.description>Mon fils a été kidnappé Ma propre chair.. sang...</MySonWasKidnapped.stages.my_son_was_kidnapped.description>
```suggestion
  <MySonWasKidnapped.stages.my_son_was_kidnapped.description>Mon fils a été kidnappé. Ma propre chair.. sang...</MySonWasKidnapped.stages.my_son_was_kidnapped.description>
```

2019-05-17 19:11 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyHusbandWasKidnapped.stages.my_husband_was_kidnapped.description>Mon époux a été kidnappé.Je suis seule..</MyHusbandWasKidnapped.stages.my_husband_was_kidnapped.description>
```suggestion
  <MyHusbandWasKidnapped.stages.my_husband_was_kidnapped.description>Mon époux a été kidnappé. Je suis seule..</MyHusbandWasKidnapped.stages.my_husband_was_kidnapped.description>
```

2019-05-17 19:11 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyFianceWasKidnapped.stages.my_fiance_was_kidnapped.description>Mon fiancé a été kidnappé Un tel homme... Qui sait quelle torture l'attend?</MyFianceWasKidnapped.stages.my_fiance_was_kidnapped.des
```suggestion
  <MyFianceWasKidnapped.stages.my_fiance_was_kidnapped.description>Mon fiancé a été kidnappé. Un tel homme... Qui sait quelle torture l'attend?</MyFianceWasKidnapped.stages.my_fiance_was_kidnapped.description>
```

2019-05-17 19:12 UTC, Mihokyo commented on Languages/French/DefInjected/ThoughtDef/Desync_Thoughts_Memory_Kidnap.xml
> +  <MyLoverWasKidnapped.stages.my_lover_was_kidnapped.label>Mon amour {0} a été kidnappé.</MyLoverWasKidnapped.stages.my_lover_was_kidnapped.label>
```suggestion
  <MyLoverWasKidnapped.stages.my_lover_was_kidnapped.label>Mon amour {0} a été kidnappé(e).</MyLoverWasKidnapped.stages.my_lover_was_kidnapped.label>
```

2019-05-19 10:51 UTC, Vectorial1024 approved these changes

2019-05-19 10:52 UTC, Vectorial1024 commented
Great, now when I complete the v1.5.1 coding on my side, I will merge this into the main branch. Your contribution will also be credited.

2019-05-20 08:47 UTC, merged